import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css"
import "./globals.css";
import Footer from "./components/footer/footer";
import Navbar from "./components/navbar/navbar";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">   
     <title>FastFood</title>
      <body className={inter.className} suppressHydrationWarning={true}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
